name: deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Create and activate virtual environment
      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Deploy to server
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            # Navigate to project directory
            cd fastapi-book-project-hng12-stage-2-task

            # Pull latest changes
            git fetch --all
            git pull origin main

            # Stop existing application
            pkill -f "uvicorn main:app" || true

            # Start application
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
