name: deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Deploy to server
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            echo "Starting deployment..."

            # Navigate to project directory
            cd fastapi-book-project-hng12-stage-2-task

            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git pull origin main

            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1

            # Install dependencies
            echo "Installing dependencies..."
            pip install -r requirements.txt || exit 1

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            # Verify application is running
            sleep 8
            if pgrep -f "uvicorn main:app" > /dev/null; then
              echo "Application started successfully"
            else
              echo "Failed to start application"
              tail -n 50 app.log
              exit 1
            fi
